baseURL = "https://lybra-bee.github.io/AI-blog/"
languageCode = "ru"
title = "AI Blog"
theme = "ananke"
defaultContentLanguage = "ru"
paginate = 5
enableRobotsTXT = true


[params]
  description = "Блог о нейросетях, ИИ и высоких технологиях"
  images = ["images/og-image.png"]

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/AI-blog/"
    weight = 1
  [[menu.main]]
    name = "Статьи"
    url = "/AI-blog/posts/"
    weight = 2
  [[menu.main]]
    name = "Галерея"
    url = "/AI-blog/gallery/"
    weight = 3
  [[menu.main]]
    name = "Обо мне"
    url = "/AI-blog/about/"
    weight = 4

# Чтобы подавлять предупреждение Goldmark raw HTML (если используете)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
