name: Generate & Deploy AI Blog

# Запуск:
# - по CRON каждый день в 06:00 UTC
# - вручную через workflow_dispatch
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  generate-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Устанавливаем зависимости Python
      - name: Install Python deps
        run: |
          pip install requests pillow

      # 4. Генерируем новую статью + изображение
      - name: Generate new content
        run: python3 scripts/generate_content.py

      # 5. Настройка Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'
          extended: true

      # 6. Сборка Hugo-сайта
      - name: Build Hugo site
        run: hugo --minify

      # 7. Публикация в gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
