name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # 2. Устанавливаем Python для генерации контента
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Устанавливаем зависимости для Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow

      # 4. Генерация контента
      - name: Generate content
        run: |
          python content_generator.py

      # 5. Устанавливаем Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.0'
          extended: true

      # 6. Сборка Hugo сайта
      - name: Build Hugo site
        run: hugo --minify

      # 7. Публикуем в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
