name: Generate Daily Content

on:
  schedule:
    - cron: '0 0 * * *'  # каждый день в полночь
  workflow_dispatch:       # возможность запускать вручную

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # 1. Получаем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Настраиваем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Устанавливаем зависимости для скрипта генерации
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests Pillow openai

    # 4. Запускаем скрипт генерации контента
    - name: Run content generator
      run: python content_generator.py

    # 5. Коммитим и пушим сгенерированный контент
    - name: Commit generated content
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add content/posts
        git add assets/images || echo "No images generated"
        git commit -m "📝 Generate daily content" || echo "No changes to commit"
        git push origin main

